# Generated by Django 3.0.8 on 2022-07-27 22:50

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=20)),
                ('set_curation', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('brand_name_eng', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_img_logo', models.ImageField(upload_to=api.models.brand_path)),
                ('brand_link', models.URLField()),
                ('brand_desc', models.TextField()),
                ('brand_img_bg', models.ImageField(upload_to=api.models.brand_path)),
                ('curation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('goods', 'Goods'), ('health', 'Health')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_type', models.CharField(choices=[('founder-story', 'founder-story'), ('daily-curation', 'daily-curation')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('tag_arr', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode_num', models.IntegerField(blank=True, null=True)),
                ('img_main', models.ImageField(upload_to=api.models.magazine_path)),
                ('img_header', models.ImageField(upload_to=api.models.magazine_path)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to=api.models.product_path)),
                ('product_img_detail', models.ImageField(upload_to=api.models.product_path)),
                ('custom_flag', models.BooleanField(default=False)),
                ('discount_flag', models.BooleanField(default=False)),
                ('delivery_cycle', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간'), ('weekly/monthly', '주간/월간')], max_length=20)),
                ('delivery_cycle_detail', models.TextField(blank=True, null=True)),
                ('min_price', models.IntegerField()),
                ('min_std_price', models.FloatField(blank=True, null=True)),
                ('max_std_price', models.FloatField(blank=True, null=True)),
                ('star_rate_avg', models.FloatField(default=0.0)),
                ('purchase_link', models.URLField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_product', to='api.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rate', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)])),
                ('review_tag_arr', models.TextField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_img_main', models.ImageField(upload_to=api.models.review_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='api.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('answer_num', models.IntegerField()),
                ('type_arr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('yogurt', '그릭요거트'), ('salad', '샐러드'), ('fried-rice', '도시락/볶음밥'), ('cereal', '그래놀라(시리얼)'), ('bread', '빵'), ('chicken', '닭가슴살'), ('milk', '우유/두유'), ('shake', '쉐이크'), ('tea', '차'), ('coffee-beans', '원두커피'), ('coffee-capsule', '캡슐커피'), ('coffee-cold', '원액커피'), ('pad', '생리용품'), ('teeth', '치아 관리'), ('pack', '스킨케어팩(팩)'), ('lens_cotton_collagen', '렌즈, 화장솜, 콜라겐'), ('shaver', '면도기'), ('lacto', '유산균'), ('care-pack', '개인 맞춤 케어 영양제 팩(팩)'), ('protein', '프로틴')], max_length=20)),
                ('type_desc', models.CharField(max_length=100)),
                ('type_desc_detail', models.CharField(max_length=100)),
                ('type_tag_arr', models.TextField(blank=True, null=True)),
                ('type_img_footer', models.FileField(upload_to=api.models.type_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_result', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_surveyresult', to='api.Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_surveyresult', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_img', models.ImageField(blank=True, upload_to=api.models.review_media_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reviewmedia', to='api.Review')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_product', to='api.Type'),
        ),
        migrations.CreateModel(
            name='MagazineContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_title', models.CharField(blank=True, max_length=100, null=True)),
                ('detail_content', models.TextField(blank=True, null=True)),
                ('detail_img', models.ImageField(blank=True, null=True, upload_to=api.models.magazine_path)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_magazinecontent', to='api.Brand')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_magazinecontent', to='api.Magazine')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_brand', to='api.Type'),
        ),
    ]
