# Generated by Django 3.0.8 on 2022-07-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(choices=[('yogurt', '그릭요거트'), ('salad', '샐러드'), ('fried-rice', '도시락/볶음밥'), ('cereal', '그래놀라(시리얼)'), ('bread', '빵'), ('chicken', '닭가슴살'), ('milk', '우유/두유'), ('shake', '쉐이크'), ('tea', '차'), ('coffee-beans', '원두커피'), ('coffee-capsule', '캡슐커피'), ('coffee-cold', '원액커피'), ('pad', '생리용품'), ('teeth', '치아 관리'), ('pack', '스킨케어팩(팩)'), ('lens_cotton_collagen', '렌즈, 화장솜, 콜라겐'), ('shaver', '면도기'), ('lacto', '유산균'), ('supplement-pack', '개인 맞춤 케어 영양제 팩(영양제)'), ('protein', '프로틴')], max_length=20),
        ),
    ]
