# Generated by Django 3.0.8 on 2022-07-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmedia',
            name='img_num',
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reviewmedia', to='api.Review'),
        ),
    ]
