# Generated by Django 3.0.8 on 2022-07-19 19:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='episode_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='magazine_type',
            field=models.CharField(choices=[('founder-story', 'founder-story'), ('daily-curation', 'daily-curation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.magazine_path),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='tag_arr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazinecontent',
            name='detail_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazinecontent',
            name='detail_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
