# Generated by Django 3.0.8 on 2022-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='intro_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
