# Generated by Django 3.0.8 on 2022-07-29 02:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220728_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinecontent',
            name='detail_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.magazine_media_path),
        ),
    ]
