# Generated by Django 3.0.8 on 2022-07-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220722_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='order',
        ),
    ]
