# Generated by Django 3.0.8 on 2022-07-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220708_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('answer_num', models.IntegerField()),
                ('type_arr', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='magazine_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazinecontent_brand', to='api.MagazineContent'),
        ),
    ]
