# Generated by Django 3.0.8 on 2022-07-09 17:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220709_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.brand_path),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.brand_path),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.magazine_path),
        ),
        migrations.AlterField(
            model_name='magazinecontent',
            name='detail_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.magazine_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_main_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.product_path),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.product_path),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_main_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.review_path),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='review_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.review_path),
        ),
    ]
