# Generated by Django 3.0.8 on 2022-07-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220710_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(choices=[('Milk', 'Milk'), ('Shake', 'Shake'), ('Yogurt', 'Yogurt'), ('Salad', 'Salad'), ('FriedRice', 'FriedRice'), ('Cereal', 'Cereal'), ('Bread', 'Bread'), ('Chicken', 'Chicken'), ('CoffeeCold', 'CoffeeCold'), ('CoffeeBeans', 'CoffeeBeans'), ('CoffeeCapsule', 'CoffeeCapsule'), ('Tea', 'Tea'), ('ShampooBar', 'ShampooBar'), ('Pad', 'Pad'), ('Soap', 'Soap'), ('Teeth', 'Teeth'), ('Pack', 'Pack'), ('Cotton', 'Cotton'), ('Lens', 'Lens'), ('Shaver', 'Shaver'), ('Lacto', 'Lacto'), ('Supplement', 'Supplement'), ('CarePack', 'CarePack'), ('Protein', 'Protein'), ('Collagen', 'Collagen')], max_length=20),
        ),
    ]
