# Generated by Django 3.0.8 on 2022-07-17 02:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220710_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmedia',
            name='review_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.review_media_path),
        ),
    ]
