# Generated by Django 3.0.8 on 2022-07-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220717_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmedia',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewMedia', to='api.Review'),
        ),
    ]
